In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
customers = pd.read_csv("../data/customers.csv", low_memory=False)
loans = pd.read_csv("../data/loans.csv", low_memory=False)
applications = pd.read_csv("../data/applications.csv", low_memory=False)
transactions = pd.read_csv("../data/transactions.csv", low_memory=False)
defaults = pd.read_csv("../data/defaults.csv", low_memory=False)
branches = pd.read_csv("../data/branches.csv", low_memory=False)

In [29]:
customers.info()
customers.describe()
customers.head()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer_ID              70000 non-null  str
 1   Full_Name                70000 non-null  str
 2   Contact_Number           70000 non-null  int64
 3   Email                    70000 non-null  str
 4   Address                  70000 non-null  str
 5   Age                      70000 non-null  int64
 6   Gender                   70000 non-null  str
 7   Marital_Status           70000 non-null  str
 8   Employment_Status        70000 non-null  str
 9   Annual_Income            70000 non-null  int64
 10  Credit_Score             70000 non-null  int64
 11  Region                   70000 non-null  str
 12  Account_Tenure           70000 non-null  str
 13  Relationship_Manager_ID  70000 non-null  str
dtypes: int64(4), str(10)
memory usage: 7.5 MB

,Customer_ID,Full_Name,Contact_Number,Email,Address,Age,Gender,Marital_Status,Employment_Status,Annual_Income,Credit_Score,Region,Account_Tenure,Relationship_Manager_ID
0,C000001,Shayak Kumar,1549750578,saxenaindrans@gopal-krishnan.com,"27/062\nSangha Nagar, Bongaigaon 736150",53,Male,Single,Unemployed,886810,433,North,12 Years,RM0015
1,C000002,Divij Ghosh,2121540709,ramanindranil@tella.com,"H.No. 20, Edwin Circle\nKatihar 892167",62,Female,Single,Self-Employed,396746,418,West,10 Years,RM0276
2,C000003,Rhea Bhargava,910320534937,bahlelakshi@mall.info,"67/386\nComar Nagar, Chapra 137669",62,Other,Single,Self-Employed,1118591,736,Northeast,9 Years,RM0098
3,C000004,Indrans Walia,6566372162,akadakia@yahoo.com,88\nDhillon Ganj\nJamshedpur-816278,59,Female,Single,Salaried,524075,353,Central,11 Years,RM0231
4,C000005,Saanvi Chad,9281095585,arhaan11@master.net,"011, Kunda Marg\nHyderabad-505161",56,Male,Single,Self-Employed,1219355,735,West,1 Years,RM0107

In [30]:
loans.info()
loans.describe()
loans.head()

<class 'pandas.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Loan_ID               90000 non-null  str
 1   Customer_ID           90000 non-null  str
 2   Loan_Amount           90000 non-null  int64
 3   Interest_Rate         90000 non-null  float64
 4   Loan_Term             90000 non-null  int64
 5   Disbursal_Date        90000 non-null  str
 6   Repayment_Start_Date  90000 non-null  str
 7   Repayment_End_Date    90000 non-null  str
 8   Loan_Status           90000 non-null  str
 9   Overdue_Amount        90000 non-null  int64
 10  EMI_Amount            90000 non-null  int64
 11  Collateral_Details    59806 non-null  str
dtypes: float64(1), int64(4), str(7)
memory usage: 8.2 MB

,Loan_ID,Customer_ID,Loan_Amount,Interest_Rate,Loan_Term,Disbursal_Date,Repayment_Start_Date,Repayment_End_Date,Loan_Status,Overdue_Amount,EMI_Amount,Collateral_Details
0,L000001,C045929,4030468,8.45,24,2023-03-25,2023-04-25,2025-03-25,Active,0,18668,Property
1,L000002,C038991,3498647,11.90,48,2023-10-23,2023-11-23,2027-10-23,Closed,44003,36012,Property
2,L000003,C046662,4871438,9.74,24,2024-07-30,2024-08-30,2026-07-30,Overdue,0,26347,NaN
3,L000004,C040268,541515,13.55,24,2024-11-22,2024-12-22,2026-11-22,Active,0,16106,NaN
4,L000005,C067057,631036,10.10,36,2024-03-30,2024-04-30,2027-03-30,Overdue,0,10127,NaN

In [31]:
applications.info()
applications.describe()
applications.head()

<class 'pandas.DataFrame'>
RangeIndex: 82600 entries, 0 to 82599
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Application_ID    82600 non-null  str
 1   Loan_ID           70000 non-null  str
 2   Customer_ID       82600 non-null  str
 3   Application_Date  82600 non-null  str
 4   Approval_Date     70000 non-null  str
 5   Loan_Purpose      82600 non-null  str
 6   Source_Channel    82600 non-null  str
 7   Processing_Fee    82600 non-null  int64
 8   Approval_Status   82600 non-null  str
 9   Rejection_Reason  12600 non-null  str
dtypes: int64(1), str(9)
memory usage: 6.3 MB

,Application_ID,Loan_ID,Customer_ID,Application_Date,Approval_Date,Loan_Purpose,Source_Channel,Processing_Fee,Approval_Status,Rejection_Reason
0,A000001,L000001,C000001,2022-05-11,2020-10-02,Business,Agent,6427,Approved,NaN
1,A000002,L000002,C000002,2022-03-18,2022-11-29,Education,Online,8605,Approved,NaN
2,A000003,L000003,C000003,2022-01-17,2023-07-01,Business,Online,1450,Approved,NaN
3,A000004,L000004,C000004,2019-03-09,2024-08-30,Home Renovation,Agent,8171,Approved,NaN
4,A000005,L000005,C000005,2024-07-18,2020-03-18,Education,Branch,4931,Approved,NaN

In [32]:
transactions.info()
transactions.describe()
transactions.head()

<class 'pandas.DataFrame'>
RangeIndex: 495000 entries, 0 to 494999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Transaction_ID     495000 non-null  str
 1   Loan_ID            495000 non-null  str
 2   Customer_ID        495000 non-null  str
 3   Transaction_Date   495000 non-null  str
 4   Payment_Type       495000 non-null  str
 5   Amount             495000 non-null  int64
 6   Overdue_Fee        495000 non-null  int64
 7   Remaining_Balance  495000 non-null  int64
 8   Mode_of_Payment    495000 non-null  str
dtypes: int64(3), str(6)
memory usage: 34.0 MB

,Transaction_ID,Loan_ID,Customer_ID,Transaction_Date,Payment_Type,Amount,Overdue_Fee,Remaining_Balance,Mode_of_Payment
0,T00000001,L005588,C050792,2021-04-30,EMI,46099,1313,1513669,NEFT
1,T00000002,L019942,C008919,2021-12-14,Penalty,43648,4852,901455,UPI
2,T00000003,L014848,C016745,2021-01-26,EMI,1810,0,1922629,Cash
3,T00000004,L041104,C039957,2021-02-18,Penalty,8607,708,213581,UPI
4,T00000005,L002488,C056156,2024-12-07,Penalty,34720,0,411621,UPI

In [33]:
defaults.info()
defaults.describe()
defaults.head()

<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Default_ID       9000 non-null   str
 1   Loan_ID          9000 non-null   str
 2   Customer_ID      9000 non-null   str
 3   Default_Date     9000 non-null   str
 4   Default_Amount   9000 non-null   int64
 5   Default_Reason   9000 non-null   str
 6   Recovery_Status  6015 non-null   str
 7   Recovery_Amount  9000 non-null   int64
 8   Legal_Action     9000 non-null   str
dtypes: int64(2), str(7)
memory usage: 632.9 KB

,Default_ID,Loan_ID,Customer_ID,Default_Date,Default_Amount,Default_Reason,Recovery_Status,Recovery_Amount,Legal_Action
0,D000001,L007312,C007312,2022-07-20,94480,Job Loss,Full,30360,Yes
1,D000002,L028234,C028234,2023-09-23,10912,Job Loss,Partial,0,Yes
2,D000003,L008319,C008319,2024-08-04,73711,Other,NaN,9866,Yes
3,D000004,L046668,C046668,2021-10-16,48955,Other,NaN,0,Yes
4,D000005,L082934,C082934,2024-10-07,56952,Medical Emergency,NaN,0,No

In [34]:
branches.info()
branches.describe()
branches.head()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Branch_ID                   50 non-null     str
 1   Branch_Name                 50 non-null     str
 2   Region                      50 non-null     str
 3   Total_Customers             50 non-null     int64
 4   Total_Active_Loans          50 non-null     int64
 5   Delinquent_Loans            50 non-null     int64
 6   Loan_Disbursement_Amount    50 non-null     int64
 7   Avg_Processing_Time         50 non-null     int64
 8   Relationship_Manager_Count  50 non-null     int64
dtypes: int64(6), str(3)
memory usage: 3.6 KB

,Branch_ID,Branch_Name,Region,Total_Customers,Total_Active_Loans,Delinquent_Loans,Loan_Disbursement_Amount,Avg_Processing_Time,Relationship_Manager_Count
0,B001,"Dhar, Kant and Madan",West,2891,279,21,341680882,6,29
1,B002,Shan Group,East,4459,1201,149,96549019,8,35
2,B003,Sachdev-Banerjee,Central,2504,122,168,445787808,12,48
3,B004,Kapadia-Brar,East,1542,1422,96,353934299,9,50
4,B005,"Mangal, Kaur and Borde",South,945,1613,87,311637902,11,10

In [35]:
customers.isnull().sum()

Customer_ID                0
Full_Name                  0
Contact_Number             0
Email                      0
Address                    0
Age                        0
Gender                     0
Marital_Status             0
Employment_Status          0
Annual_Income              0
Credit_Score               0
Region                     0
Account_Tenure             0
Relationship_Manager_ID    0
dtype: int64

In [37]:
# Fix for Credit_Score (Numeric)
customers['Credit_Score'] = customers['Credit_Score'].fillna(customers['Credit_Score'].median())

# Fix for Employment_Status (Categorical)
customers['Employment_Status'] = customers['Employment_Status'].fillna(customers['Employment_Status'].mode()[0])

In [38]:
customers.drop_duplicates(inplace=True)
loans.drop_duplicates(inplace=True)
applications.drop_duplicates(inplace=True)
transactions.drop_duplicates(inplace=True)
defaults.drop_duplicates(inplace=True)
branches.drop_duplicates(inplace=True)

In [40]:
applications['Application_Date'] = pd.to_datetime(applications['Application_Date'], errors='coerce')
transactions['Transaction_Date'] = pd.to_datetime(transactions['Transaction_Date'], errors='coerce')
defaults['Default_Date'] = pd.to_datetime(defaults['Default_Date'], errors='coerce')

In [41]:
def remove_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    return df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

In [42]:
loans = remove_outliers(loans, 'Loan_Amount')
loans = remove_outliers(loans, 'Interest_Rate')
defaults = remove_outliers(defaults, 'Default_Amount')

In [43]:
customers.to_csv("../data/customers_cleaned.csv", index=False)
loans.to_csv("../data/loans_cleaned.csv", index=False)
applications.to_csv("../data/applications_cleaned.csv", index=False)
transactions.to_csv("../data/transactions_cleaned.csv", index=False)
defaults.to_csv("../data/defaults_cleaned.csv", index=False)
branches.to_csv("../data/branches_cleaned.csv", index=False)

### Task 1 – Data Cleaning Summary
- Handled missing values using median/mode
- Removed duplicate records
- Standardized date formats
- Treated outliers using IQR method
- Prepared clean datasets for analysis